#import "@preview/tidy:0.4.3"
#import "../slide.typ" as sdu

#let primary = rgb("#9c0b15")
#let primary-soft = rgb("#ce858a")
#let ink = rgb("#202124")
#let muted = rgb("#666a70")
#let paper = rgb("#fbfaf8")
#let panel = rgb("#ffffff")
#let rule = rgb("#e5d8d8")

#let api-colors = (
    default: rgb("#f3eeee"),
    content: rgb("#f4d7da"),
    str: rgb("#e7f0ff"),
    string: rgb("#e7f0ff"),
    int: rgb("#fff0cf"),
    bool: rgb("#e2f4df"),
    datetime: rgb("#e9e1ff"),
    dictionary: rgb("#ececec"),
    array: rgb("#ececec"),
    arguments: rgb("#ececec"),
    function: rgb("#f7e0f4"),
    "none": rgb("#f2d2ca"),
    "auto": rgb("#f2d2ca"),
    "signature-func-name": primary,
)

#set document(
    title: "SDU OS Slide Manual",
    author: "arshtyi",
)
#set page(
    paper: "a4",
    margin: (x: 2.1cm, top: 2.2cm, bottom: 2.4cm),
    fill: paper,
    header: context {
        if counter(page).get().first() > 1 {
            set text(size: 8.5pt, fill: muted)
            grid(
                columns: (1fr, auto),
                align: (left, right),
                [SDU OS Slide], counter(page).display(),
            )
            v(3pt)
            line(length: 100%, stroke: 0.4pt + rule)
        }
    },
)
#set text(
    size: 10.5pt,
    fill: ink,
    font: ("Source Han Sans SC", "Calibri"),
)
#set par(justify: true, leading: 0.72em)
#set list(indent: 1.2em, body-indent: 0.45em)
#show link: set text(fill: primary)
#show raw: set text(font: ("IBM Plex Mono", "Source Han Sans SC"))
#show raw.where(block: false): box.with(
    fill: rgb("#f4eeee"),
    inset: (x: 0.28em, y: 0.02em),
    outset: (y: 0.18em),
    radius: 2pt,
)
#show raw.where(block: true): it => block(
    fill: panel,
    stroke: 0.6pt + rule,
    inset: 10pt,
    radius: 4pt,
    width: 100%,
    it,
)
#show heading.where(level: 1): it => {
    pagebreak(weak: true)
    block(below: 1.1em, {
        text(size: 23pt, weight: "bold", fill: primary, it.body)
        v(5pt)
        line(length: 100%, stroke: 1.2pt + primary)
    })
}
#show heading.where(level: 2): it => block(
    above: 1.0em,
    below: 0.55em,
    text(size: 16pt, weight: "bold", fill: primary, it.body),
)
#show heading.where(level: 3): it => block(
    above: 0.8em,
    below: 0.35em,
    text(size: 12.5pt, weight: "bold", fill: ink, it.body),
)
#show heading.where(level: 4): it => block(
    above: 0.5em,
    below: 0.25em,
    text(size: 10.5pt, weight: "bold", fill: primary, it.body),
)

#let callout(title, body) = block(
    width: 100%,
    fill: panel,
    stroke: (left: 3pt + primary, rest: 0.6pt + rule),
    inset: (x: 12pt, y: 9pt),
    radius: 4pt,
    [
        #text(weight: "bold", fill: primary, title)
        #parbreak()
        #body
    ],
)

#let module-reference(title, path, description) = {
    heading(level: 2, title)
    text(fill: muted, description)
    v(0.6em)
    let docs = tidy.parse-module(
        read(path),
        name: title,
        label-prefix: title + "-",
        scope: (sdu: sdu),
    )
    tidy.show-module(
        docs,
        style: tidy.styles.default,
        first-heading-level: 2,
        show-module-name: false,
        show-outline: true,
        sort-functions: none,
        colors: api-colors,
        omit-private-definitions: true,
        omit-private-parameters: true,
        local-names: (
            parameters: [参数],
            default: [默认值],
            variables: [变量],
        ),
    )
}

#align(center + horizon, block(height: 23cm, {
    image("../assets/sdu.png", width: 6.4cm)
    v(1.6cm)
    text(size: 30pt, weight: "bold", fill: primary)[SDU OS Slide]
    v(0.35cm)
    text(size: 15pt, fill: muted)[Typst 幻灯片模板使用手册]
    v(1.2cm)
    line(length: 8cm, stroke: 1pt + primary-soft)
    v(1.2cm)
    text(size: 10pt, fill: muted)[API reference generated by tidy]
    v(0.2cm)
    text(size: 10pt, fill: muted)[#datetime.today().display("[year]-[month]-[day]")]
}))

#pagebreak()

#outline(title: [目录], depth: 3)

= 项目概览

SDU OS Slide 是一个面向山东大学操作系统课程幻灯片风格的 Typst 模板.它的核心目标是保持原幻灯片的版式特征,同时提供更适合源码维护的模块结构和增量展示能力.

#callout[页边界规则][
    一级、二级和三级标题都是幻灯片页边界：`= Section`、`== Slide` 与 `=== Topic` 都会触发换页.三级标题不会进入右侧 sidebar,但会在新页中渲染为居中的红色标题.
]

== 模块地图

#table(
    columns: (1.25fr, 2fr),
    stroke: 0.45pt + rule,
    fill: (_, row) => if row == 0 { primary } else { panel },
    inset: 7pt,
    align: (left, left),
    table.header(text(fill: white, weight: "bold")[模块], text(fill: white, weight: "bold")[职责]),
    [`slide.typ`], [对外入口,导出 `setup`、`theme`、`pause`、`meanwhile`、`jump`.],
    [`lib/theme.typ`], [页面尺寸、封面、正文页框、1/2/3 级标题页边界与 overlay 渲染入口.],
    [`lib/core/overlays.typ`], [`pause`/`meanwhile`/`jump` 的覆盖层标记、handout 与播放版渲染器.],
    [`lib/foundation/theme.typ`], [字体、颜色、页面尺寸等设计 token.],
    [`lib/components/cover.typ`], [封面页绘制.],
    [`lib/components/sidebar.typ`], [右侧目录、当前小节高亮和页内链接.],
    [`lib/utils/draw.typ`], [绘图辅助函数.],
)

= 快速开始

```typ
#import "slide.typ": setup, theme, pause, meanwhile

#show: setup.with(
    title: "SDU OS Slide",
    subtitle: "Slide for SDU OS",
    author: "arshtyi",
    term: "2026 Spring",
    date: datetime.today(),
    handout: false,
)

= Chapter
== First Slide
=== Optional Topic Slide

第一段内容
#pause
第二段内容
#meanwhile
这一段从第一层 overlay 就可见
```

`pause` 会让后续内容延迟到下一层 overlay 出现；`meanwhile` 会把后续内容重置回第一层 overlay,因此适合并行展示另一组内容.

将 `handout` 设为 `true` 可以生成阅读版 PDF：每张幻灯片只输出最终 overlay 状态,不会把 `pause` 的中间步骤展开成多页.

= 写作约定

== 标题层级

- `= 一级标题`：章节标题,进入侧栏目录并触发新页.
- `== 二级标题`：普通幻灯片标题,进入侧栏目录并触发新页.
- `=== 三级标题`：主题页标题,不进入侧栏目录,但会触发新页并居中显示.
- 更深层级标题：也会继承模板的换页规则；通常建议少用,避免目录和页边界过碎.

== 覆盖层

覆盖层按当前幻灯片的顶层内容顺序工作.隐藏内容使用 `hide` 保留占位,因此页面布局在不同 overlay 之间会更稳定.

```typ
Always visible
#pause
Visible on overlay 2
#pause
Visible on overlay 3
#meanwhile
Also visible on overlay 1
```

== 播放版与阅读版

```typ
#show: setup.with(
    title: "Lecture",
    handout: false, // presentation: keep every overlay
)
```

```typ
#show: setup.with(
    title: "Lecture",
    handout: true, // handout: final state only
)
```

这与 Touying 的播放/讲义分工一致：播放版保留 reveal 的节奏,阅读版保留每页最终信息密度.

= API Reference

依赖于 `tidy` 生成的 API 文档.

== slide

`slide.typ` 是使用者唯一需要直接导入的入口文件.它重新导出以下符号：

#table(
    columns: (1fr, 2fr),
    stroke: 0.45pt + rule,
    fill: (_, row) => if row == 0 { primary } else { panel },
    inset: 7pt,
    table.header(text(fill: white, weight: "bold")[导出], text(fill: white, weight: "bold")[说明]),
    [`setup`], [模板主入口,通常通过 `#show: setup.with(..)` 使用.],
    [`theme`], [设计 token 字典,可在用户文档中读取字体、颜色和页面尺寸.],
    [`pause`], [进入下一层 overlay.],
    [`meanwhile`], [把后续内容重置为从第一层 overlay 可见.],
    [`jump`], [覆盖层底层跳转标记,供高级控制使用.],
)

#module-reference(
    "theme",
    "../lib/theme.typ",
    [主模板设置函数,负责把文档转换成 SDU OS slide 样式.],
)

#module-reference(
    "overlays",
    "../lib/core/overlays.typ",
    [覆盖层标记与渲染逻辑,提供 Touying 风格的增量展示能力.],
)

#module-reference(
    "foundation-theme",
    "../lib/foundation/theme.typ",
    [集中存放字体、颜色和页面尺寸的设计 token.],
)

#module-reference(
    "cover",
    "../lib/components/cover.typ",
    [封面组件,绘制 logo、标题、徽章和装饰圆.],
)

#module-reference(
    "sidebar",
    "../lib/components/sidebar.typ",
    [正文页右侧导航组件,生成可点击目录并高亮当前小节.],
)

#module-reference(
    "draw",
    "../lib/utils/draw.typ",
    [低层绘图辅助函数.],
)
